# Generated by Django 3.0.1 on 2019-12-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('company_tel', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_tel', models.CharField(blank=True, max_length=20)),
                ('customer_address', models.CharField(blank=True, max_length=20)),
                ('customer_age', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('num_familymembers', models.DecimalField(decimal_places=0, max_digits=10)),
                ('register_date', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_cost', models.DecimalField(decimal_places=0, max_digits=20)),
                ('product_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('store_tel', models.CharField(max_length=20)),
                ('store_address', models.CharField(max_length=20)),
                ('store_district', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('warehouse_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_method', models.CharField(max_length=20)),
                ('discount_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('size', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.CharField(max_length=20)),
                ('storage_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Warehouse')),
            ],
            options={
                'unique_together': {('product_id', 'warehouse_id', 'shoe_size')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.CharField(max_length=2, unique=True)),
                ('inventory_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
            options={
                'unique_together': {('product_id', 'store_id', 'shoe_size')},
            },
        ),
    ]
