# Generated by Django 3.0.1 on 2019-12-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='store_id',
        ),
    ]
