# Generated by Django 3.0.1 on 2019-12-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_order_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default='00001', on_delete=django.db.models.deletion.CASCADE, to='home.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='home.Store'),
        ),
    ]
