# Generated by Django 3.0.1 on 2019-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191230_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='average_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shoe_size',
            field=models.CharField(max_length=2),
        ),
    ]
