# Generated by Django 3.0.1 on 2019-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191230_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='average_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
