# Generated by Django 3.0 on 2020-01-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191230_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_logic',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
